# Generated by Django 2.2.7 on 2020-06-24 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_student_nome_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nome_student',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
