# Generated by Django 2.2.7 on 2020-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200822_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Temps_TP',
            field=models.IntegerField(default=5),
        ),
    ]
