# Generated by Django 2.2.7 on 2020-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_quiz_temps_tp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning_TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_TP', models.IntegerField()),
                ('id_usr', models.IntegerField()),
                ('time_in', models.DateTimeField()),
                ('time_fn', models.DateTimeField()),
                ('time_TP', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Temps_TP',
            field=models.IntegerField(default=5, verbose_name='Temps de TP min'),
        ),
    ]
