# Generated by Django 2.2.7 on 2020-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200624_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
    ]
