# Generated by Django 2.2.7 on 2020-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200624_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type_tp',
            field=models.CharField(choices=[('RC', 'RC'), ('R', 'R'), ('RL', 'RL')], default='RC', max_length=6),
        ),
    ]
