# Generated by Django 2.2.7 on 2020-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_quiz_type_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='description defult', max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type_tp',
            field=models.CharField(choices=[('RC', 'RC'), ('R', 'R'), ('RL', 'RL')], max_length=6),
        ),
    ]
