# Generated by Django 2.2.7 on 2020-09-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='email_cad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='temps_cal',
            field=models.IntegerField(default=12, verbose_name="L interval temporel de calendrier (À l'heure)"),
        ),
    ]
