# Generated by Django 2.2.7 on 2020-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200624_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fiche_tp',
            field=models.FileField(default='hhhhh.text', upload_to='uploads_tp/'),
            preserve_default=False,
        ),
    ]
