# Generated by Django 2.2.7 on 2020-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_question_fiche_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.CharField(default='module', max_length=255),
        ),
    ]
