# Generated by Django 2.2.7 on 2020-06-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='compte_rendu',
            field=models.FileField(default='defult.text', upload_to='uploads_tp/'),
            preserve_default=False,
        ),
    ]
