# Generated by Django 2.2.7 on 2020-06-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_studentanswer_compte_rendu'),
    ]

    operations = [
        migrations.CreateModel(
            name='correction_TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_rendu', models.FileField(upload_to='uploads_tp/')),
                ('module', models.CharField(default='module', max_length=255)),
                ('note', models.FloatField()),
            ],
        ),
    ]
