# Generated by Django 2.2.7 on 2020-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_correction_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction_tp',
            name='id_tp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction_tp',
            name='nome_student',
            field=models.CharField(default='module', max_length=255),
        ),
    ]
