# Generated by Django 2.2.7 on 2020-06-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20200627_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction_tp',
            name='id_tp',
        ),
    ]
