# Generated by Django 2.2.7 on 2020-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_remove_correction_tp_id_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction_tp',
            name='id_tp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
