# Generated by Django 2.2.7 on 2020-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_correction_tp_id_tp'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='compte_rendu',
            field=models.FileField(default='texte.text', upload_to='uploads_tp/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correction_tp',
            name='id_tp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='correction_tp',
            name='note',
            field=models.FloatField(default=0),
        ),
    ]
