# Generated by Django 2.2.7 on 2020-06-27 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20200627_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction_tp',
            name='id',
        ),
        migrations.AddField(
            model_name='correction_tp',
            name='user',
            field=models.OneToOneField(default= 5 , on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
