# Generated by Django 2.2.7 on 2020-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20200627_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction_tp',
            name='id_user',
            field=models.IntegerField(default=100),
        ),
    ]
