# Generated by Django 2.2.7 on 2020-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_correction_tp_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction_tp',
            name='id_tp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='correction_tp',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
